const JoueursEtRegions = {
    Alex59: 'Verte',
    Alexlesec: 'Verte',
    ArjacSeta: 'Verte',
    Balthus: 'Violet',
    biak40: 'Orange',
    BOSS: 'Rouge',
    BrG: 'Cyan',
    Bynouz: 'Violet',
    Chapelier:'Orange',
    Dunk: 'Cyan',
    El_chatardo: 'Rouge',
    Enguerand: 'Verte',
    expunk: 'Verte',
    eric: 'Rouge',
    Fao: 'Verte',
    Galahad59: 'Verte',
    Gaokerena: 'Verte',
    Helvain: 'Rouge',
    Iblis: 'Verte',
    Jarekson: 'Vert Clair',
    Jawjaw: 'Violet',
    Julo62: 'Verte',
    KENZO: 'Verte',
    Kenozan: 'Marron',
    Ketep: 'Jaune',
    Kintz: 'Violet',
    Knurlnien: 'Rouge',
    Kutchuc: 'Rouge',
    Lauzerg974: 'Rouge',
    LuciusForge: 'Violet',
    Lyhnnae: 'Jaune',
    Marzu: 'Verte',
    MaSeDrIm: 'Rouge',
    Maximork: 'Violet',
    MorpheeTheJoker: 'Violet',
    Morzaad: 'Vert Clair',
    MyNicknameIsBetterThanYours: 'Jaune',
    Nabot: 'Rouge',
    Nayko_le_Rat: 'Rouge',
    Noah: 'Verte',
    ollv: 'Verte',
    Orckel: 'Verte',
    Siilence: 'Vert Clair',
    SirThomasNoMore: 'Jaune',
    Sousou: 'Violet',
    Taybard: 'Cyan',
    Tenekha: 'Cyan',
    Thalantir: 'Cyan',
    Twerk: 'Verte',
    VargLeRedoutable: 'Cyan',
    walach: 'Verte',
    Ysardul: 'Rouge',
};
