const JoueursEtRegions = {
    Knurlnien: 'Rouge',
    Nayko_le_Rat: 'Rouge',
    Kutchuc: 'Rouge',
    Jarekson: 'Vert Clair',
    Dunk: 'Cyan',
    Thalantir: 'Cyan',
    Jawjaw: 'Violet',
    Tenekha: 'Cyan',
    LuciusForge: 'Violet',
    Sousou: 'Violet',
    Morzaad: 'Vert Clair',
    VargLeRedoutable: 'Cyan',
    Taybard: 'Cyan',
    MaSeDrIm: 'Rouge',
    BOSS: 'Rouge',
    Chapelier:'Orange',
    Lauzerg974: 'Rouge',
    El_chatardo: 'Rouge',
    biak40: 'Orange',
    Ysardul: 'Rouge',
    Helvain: 'Rouge'
};
